// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ef02.Models;

#nullable disable

namespace ef02.Migrations
{
    [DbContext(typeof(NhanVienContext))]
    [Migration("20240403065732_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ef02.Models.DuAnModel", b =>
                {
                    b.Property<int>("DuAnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DuAnId"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Moto")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenDuAn")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DuAnId");

                    b.ToTable("DuAn");
                });

            modelBuilder.Entity("ef02.Models.NhanVienModel", b =>
                {
                    b.Property<int>("NhanVienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhanVienId"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("HeSoLuong")
                        .HasColumnType("int");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NhanVienId");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("ef02.Models.PhanCongModel", b =>
                {
                    b.Property<int>("PhanCongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhanCongId"));

                    b.Property<int>("DuAnId")
                        .HasColumnType("int");

                    b.Property<int?>("DuAnModelDuAnId")
                        .HasColumnType("int");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<int?>("NhanVienModelNhanVienId")
                        .HasColumnType("int");

                    b.Property<int>("SoGioLam")
                        .HasColumnType("int");

                    b.HasKey("PhanCongId");

                    b.HasIndex("DuAnModelDuAnId");

                    b.HasIndex("NhanVienModelNhanVienId");

                    b.ToTable("PhanCong");
                });

            modelBuilder.Entity("ef02.Models.PhanCongModel", b =>
                {
                    b.HasOne("ef02.Models.DuAnModel", "DuAnModel")
                        .WithMany()
                        .HasForeignKey("DuAnModelDuAnId");

                    b.HasOne("ef02.Models.NhanVienModel", "NhanVienModel")
                        .WithMany()
                        .HasForeignKey("NhanVienModelNhanVienId");

                    b.Navigation("DuAnModel");

                    b.Navigation("NhanVienModel");
                });
#pragma warning restore 612, 618
        }
    }
}
