// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ef04.Models;

#nullable disable

namespace ef04.Migrations
{
    [DbContext(typeof(PhieuThuDBContext))]
    partial class PhieuThuDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ef04.Models.ChiTietPhieuThu", b =>
                {
                    b.Property<int>("ChiTietPhieuThuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietPhieuThuId"));

                    b.Property<int>("NguyenLieuId")
                        .HasColumnType("int");

                    b.Property<int>("PhieuThuId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongBan")
                        .HasColumnType("int");

                    b.HasKey("ChiTietPhieuThuId");

                    b.HasIndex("NguyenLieuId");

                    b.HasIndex("PhieuThuId");

                    b.ToTable("chiTietPhieus");
                });

            modelBuilder.Entity("ef04.Models.LoaiNguyenLieu", b =>
                {
                    b.Property<int>("LoaiNguyenLieuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoaiNguyenLieuId"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("LoaiNguyenLieuId");

                    b.ToTable("loaiNguyenLieus");
                });

            modelBuilder.Entity("ef04.Models.NguyenLieu", b =>
                {
                    b.Property<int>("NguyenLieuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NguyenLieuId"));

                    b.Property<string>("DonViTinh")
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("money");

                    b.Property<int>("LoaiNguyenLieuId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongKho")
                        .HasColumnType("int");

                    b.Property<string>("TenNguyenLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("NguyenLieuId");

                    b.HasIndex("LoaiNguyenLieuId");

                    b.ToTable("nguyenLieus");
                });

            modelBuilder.Entity("ef04.Models.PhieuThu", b =>
                {
                    b.Property<int>("PhieuThuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhieuThuId"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanVienLap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("money");

                    b.HasKey("PhieuThuId");

                    b.ToTable("phieuThus");
                });

            modelBuilder.Entity("ef04.Models.ChiTietPhieuThu", b =>
                {
                    b.HasOne("ef04.Models.NguyenLieu", "NguyenLieu")
                        .WithMany("ChiTietPhieuThus")
                        .HasForeignKey("NguyenLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ef04.Models.PhieuThu", "PhieuThu")
                        .WithMany("ChiTietPhieuThus")
                        .HasForeignKey("PhieuThuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguyenLieu");

                    b.Navigation("PhieuThu");
                });

            modelBuilder.Entity("ef04.Models.NguyenLieu", b =>
                {
                    b.HasOne("ef04.Models.LoaiNguyenLieu", "LoaiNguyenLieu")
                        .WithMany("NguyenLieu")
                        .HasForeignKey("LoaiNguyenLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiNguyenLieu");
                });

            modelBuilder.Entity("ef04.Models.LoaiNguyenLieu", b =>
                {
                    b.Navigation("NguyenLieu");
                });

            modelBuilder.Entity("ef04.Models.NguyenLieu", b =>
                {
                    b.Navigation("ChiTietPhieuThus");
                });

            modelBuilder.Entity("ef04.Models.PhieuThu", b =>
                {
                    b.Navigation("ChiTietPhieuThus");
                });
#pragma warning restore 612, 618
        }
    }
}
